### ISSUE TITLE
Form goes wrong when we have a muti-valued nested field

### ISSUE THREAD

**Issue by dbengsch** [kuzzleio/kuzzle-backoffice#120]
When we have a multi-valued nested field in a document, the form doesn't display correctly. The value of the field is replaced by `[object Object]`.

**Comment by AnthonySendra** [comment]
Like discussed before, I think we can auto switch to JSON view, disabled the form view and display a warning message like ~ "You document is to complicate for displaying the JSON view."

**Comment by AnthonySendra** [comment]
The form is also broken when the mapping is something like this
[things.json.txt](https://github.com/kuzzleio/kuzzle-backoffice/files/502408/things.json.txt)
