### ISSUE TITLE
New deployment build for NPM

### ISSUE THREAD

**Issue by xbill82** [kuzzleio/kuzzle-backoffice#122]

**Comment by xbill82** [comment]
## Proposal
`config/` contains some sort of _default_ configuration, which can work standalone.
`bin/start.js` generates a `config/custom.env.js`, which contains a custom config set, based on `rc` (cli arguments + env vars)
When the http server executes, the default config is _merged_ with the custom, so that custom values override the default ones.

U OK WIT IT?

**Comment by AnthonySendra** [comment]
@xbill82 How are you will merge the default config and custom?

**Comment by xbill82** [comment]
https://www.npmjs.com/package/merge

**Comment by AnthonySendra** [comment]
Okay, but you are in front-end context. You can't do `require` or something.

**Comment by xbill82** [comment]
nope, I plan to do it in the `/config/index.js` file, which is read by the http server in a Node.js context. BTW, all the front end code is transpiled by Webpack so it would work anyway

**Comment by xbill82** [comment]
After discussing the issue, we all agree on the fact that this path is a bad one. We gonna let the use manage "environments" (Kuzzle address & ports + header color) from the UI.
Closing this issue.
