### ISSUE TITLE
Updating a document gets stuck on the same route

### ISSUE THREAD

**Issue by xbill82** [kuzzleio/kuzzle-backoffice#135]
Clicking on the "Update" button in the Document Update page doesn't succeed in transitioning to the next page. The console shows the following errors from the `vue-router` (the browser is actually stuck and busy probably doing endless loops before showing the errors)

    [vue-router] Uncaught error during transition:
    Uncaught TypeError: room.unsubscribe is not a function
    Uncaught TypeError: Cannot read property 'length' of null

Steps to reproduce:

* Pick a document and click on the pencil to edit it
* edit (or not) any of the fields
* click "Update"
* See the magic (LOL)

**Comment by AnthonySendra** [comment]
fixed by #134
