### ISSUE TITLE
Homepage should not try to connect automatically to "localhost"

### ISSUE THREAD

**Issue by ballinette** [kuzzleio/kuzzle-backoffice#170]
When we launch the backoffice, it tries by default to connect to a kuzzle instance hosted locally, and then, only after a few seconds, it shows the dropdown to select the kuzzle host:
![pasted image at 2016_12_06 14_45](https://cloud.githubusercontent.com/assets/1447135/20937950/56f79732-bbe9-11e6-8c6e-293187bcc3fe.png)

We should rather ask the user to choose the environment BEFORE trying to connect to it.

The user's choice can then be saved in the localStorage for the next usages.

**Comment by AnthonySendra** [comment]
Fixed in 2.1.0
