### ISSUE TITLE
Small refactoring needed in kuzzle wrapper

### ISSUE THREAD

**Issue by xbill82** [kuzzleio/kuzzle-backoffice#175]
* some things, like performSearch and deleteDocuments may be moved to a more data-related service (or even directly in a Vuex action),
* avoid the return new Promise() statements when possible,
* some functions, like deleteDocuments have inconsistent return values.

**Comment by gandbox** [comment]
to rewrite & update, difficult to understand & follow

**Comment by ballinette** [comment]
need to recreate new issues with details when we reopen the backoffice/console roadmap.
closing this issue for now to cleanup the backlog
