### ISSUE TITLE
Bump the SDK version to follow the controller refactor

### ISSUE THREAD

**Issue by dbengsch** [kuzzleio/kuzzle-backoffice#178]
Bump SDK version to 2.3.0 after the merge of the PR kuzzleio/kuzzle#569.

See kuzzleio/sdk-javascript#152 for more details.

**Comment by ballinette** [comment]
should be 2.3.4 after the merge of  https://github.com/kuzzleio/sdk-javascript/pull/165

**Comment by ballinette** [comment]
and need also to fix `userAuthorization` service with new contoller/action names
