### ISSUE TITLE
Display users edit page

### ISSUE THREAD

**Issue by AnthonySendra** [kuzzleio/kuzzle-backoffice#184]
Linked to https://github.com/kuzzleio/kuzzle/issues/617

**Comment by xbill82** [comment]
I can actually see the Edit page for Profiles and Roles (excepted that the Update button is broken, as stated in #197 ) but I confirm that I have a nasty error when I try to edit a user:

![selection_005](https://cloud.githubusercontent.com/assets/5023426/21857420/a8129d44-d825-11e6-8635-c53171ec0257.jpg)

**Comment by AnthonySendra** [comment]
Missing part about getUserMapping
