### ISSUE TITLE
unable to create document with additional String attribute

### ISSUE THREAD

**Issue by xbill82** [kuzzleio/kuzzle-backoffice#191]
![selection_002](https://cloud.githubusercontent.com/assets/5023426/21845325/7f27d3aa-d7f2-11e6-81df-a5169a1e9f7c.jpg)

Steps to reproduce
* create a new collection (empty mapping)
* click on "new document"
* click on "new attribute"
* fill in new attribute name with type String
* create new document without ID (but filling the new attribute value)

The error says: `An error occurred while trying to update collection mapping according to the document: 
Can not set mapping for field "artistName" because type "" does not exist`

**Comment by AnthonySendra** [comment]
Probably linked to #191
