### ISSUE TITLE
Unable to see the newly created document in list

### ISSUE THREAD

**Issue by xbill82** [kuzzleio/kuzzle-backoffice#192]
Since the UI does not wait the 1s indexation delay in ES, the user cannot see a document in the list right after creating it (refreshing the page is necessary).

**Comment by AnthonySendra** [comment]
Hi @xbill82,
I have tried and can't reproduce. Could you double check please?

**Comment by xbill82** [comment]
yep it happens very very rarely. I had it once (then raised the issue) but never got it again. Should not be prioritary.

**Comment by AnthonySendra** [comment]
Fixed with `{refresh: 'wait_for'}`
