### ISSUE TITLE
Edit document form is broken

### ISSUE THREAD

**Issue by xbill82** [kuzzleio/kuzzle-backoffice#193]
When clicking on the pencil icon of a document in the list, the user lands on the new document creation form.

**Comment by xbill82** [comment]
Reopening as the attribute fields in the form are not filled
![selection_003](https://cloud.githubusercontent.com/assets/5023426/21853585/0b95879a-d818-11e6-88b4-2f3c6c676eaa.jpg)
Works like a charm in JSON mode, btw.

**Comment by xbill82** [comment]
2 problems here

* When the form is filled, some fields are not. Example: I have a `date` field of `type: "date"` with `format: "dd/MM/yyyy||epoch_millis"`, which only works when the date is provided as a string in the first form.
* When switching to JSON mode and back, the form is pristine.

**Comment by xbill82** [comment]
Going to focus on the second issue pointed above (as we are not able to manage dates yet)

**Comment by AnthonySendra** [comment]
For the first issue, I have opened a new issue here:https://github.com/kuzzleio/kuzzle-backoffice/issues/200
