### ISSUE TITLE
Try to connect to localhost even on environment switch

### ISSUE THREAD

**Issue by AnthonySendra** [kuzzleio/kuzzle-backoffice#216]
* Shut down kuzzle on localhost
* Run BO
* The BO try to connect to localhost
* Create a new environment where Kuzzle is started
* The BO still try to connect to localhost

**Comment by jenow** [comment]
See https://github.com/kuzzleio/sdk/issues/16

**Comment by gandbox** [comment]
Waiting for new SDK
