### ISSUE TITLE
Loader automatically displayed when deleting users on a second delete

### ISSUE THREAD

**Issue by BaptisteKaliop** [kuzzleio/kuzzle-backoffice#218]
Just updated on RC9 + BO 2.0

I wanted to delete users with the back-office. 
When you delete users, on the second (and further) times, the backoffice automatically display the loader 

Steps to reproduce : 
- Create two users
- Delete one 
- BO display loading only after clicking "I'm sure"
- Delete another user
- BO display automatically the loading animation

**Comment by AnthonySendra** [comment]
Hello @BaptisteKaliop.

Can't reproduce on the current 2.x branch (http://kuzzle-backoffice-2.netlify.com).
Could you confirm this is not a bug anymore please?

**Comment by BaptisteKaliop** [comment]
Can't reproduce anymore. It looks fixed :)

thanks
