### ISSUE TITLE
JSON view change json structure

### ISSUE THREAD

**Issue by neolas** [kuzzleio/kuzzle-backoffice#230]
Hi,

I'm on an old version (branch develop on commit 3c02fc79d5d4ec3910d3d1146221e830e1a20d53 of 13/jan) I experiment an issue on JSON Viewer in BO. I wait 1.0 before upgrade.

On this version, all arrays are changed in JSON object : 
_Real data in Kuzzle :_ 
references:[{'field':'test1'},{'field':'test2'}]

_will be display like this :_ 
references:{"0":{'field':'test1'},"1":{'field':'test2'}}

Perhaps it's solved in next commits. 

Cheers,

**Comment by AnthonySendra** [comment]
Will be released in 2.1
