### ISSUE TITLE
Edit an user deletes his password

### ISSUE THREAD

**Issue by BaptisteKaliop** [kuzzleio/kuzzle-backoffice#252]
When you edit an user in the backoffice, the password field disappear.

I suspect the kuzzle-auth-strategy-local to be the problem since there is a pipe that removes the password (why, tho')

Using : kuzzle-backoffice-2.netlify.com

**Comment by jenow** [comment]
We do not how the password, the plugin will automatically remove this field. You can modify the password by manually adding the password field in your json while editing the user.
