### ISSUE TITLE
Using rawJsonMode to perform query display only one row in json input

### ISSUE THREAD

**Issue by BaptisteKaliop** [kuzzleio/kuzzle-backoffice#253]
When using the rawJsonMode, the json input display only one row.

I guess it should be displayed with the same height than the basic mode 

![download 1](https://cloud.githubusercontent.com/assets/24288932/25475241/62e625f6-2b36-11e7-8305-bae890de8930.png)

**Comment by AnthonySendra** [comment]
Fixed on branch 2.x
Waiting for the next release (2.1.0)
