### ISSUE TITLE
Display bug on collection's watch tab

### ISSUE THREAD

**Issue by dbengsch** [kuzzleio/kuzzle-backoffice#286]
On collection's watch tab, when the main page display starts to have a scroll bar, it is not possible to interact with both filter builder and published messages / documents; the arrows won't unfold, and when unfolded, will fold as soon as we try to scroll.

**Comment by dbengsch** [comment]
It might come from the `scroll on new messages` that is enabled by default

**Comment by jenow** [comment]
Yes this is because scroll on new messages is enabled. I am going to put the whole message list inside a container which will have a scroll bar
