### ISSUE TITLE
[Security > Roles > Create] Once an error occured, it is impossible to submit the creation

### ISSUE THREAD

**Issue by dbengsch** [kuzzleio/kuzzle-backoffice#287]
In role creation, once an error has occurred, in my case:
```
An error occurred while creating role: 
Invalid definition for [document]: "actions" attribute missing
```
It is not possible to submit the form anymore (even if the JSON has been corrected)

Same problem with profile, user and document creation

Browser: Chrome 56.0.2924.76

**Comment by dbengsch** [comment]
Seems corrected by https://github.com/kuzzleio/kuzzle-backoffice/pull/282

**Comment by samniisan** [comment]
Fixed by @jenow https://github.com/kuzzleio/kuzzle-backoffice/pull/303#pullrequestreview-44765858 and merged
