### ISSUE TITLE
Sort on collection triggers an error

### ISSUE THREAD

**Issue by dbengsch** [kuzzleio/kuzzle-backoffice#296]
When I specify a sort on a text field, an error occurs and no result is shown:

`An error occured while performing search:
Fielddata is disabled on text fields by default. Set fielddata=true on [some] in order to load fielddata in memory by univerting the inverted indexs. Note that this can however use significant memory. Alternatively use a keyword field instead.`

By the way, the error message wraps by cutting the word Alternatively which is weird.

**Comment by jenow** [comment]
This is a normal behavior
