### ISSUE TITLE
Make it possible to install without being root

### ISSUE THREAD

**Issue by gggeek** [kuzzleio/kuzzle-backoffice#319]
The current installation procedure requires being root on the computer. This should not be a requirement.
It is also necessary to be root when doing a manual build of the app, for the `npm run build` step. This should also not require root permissions.

**Comment by xbill82** [comment]
@gggeek if npm asks you for root permissions for a `npm run build` there's something weird going on with your setup.
Besides that, what do you exactly mean by "installation"? If you mean `npm install -g`, it is quite normal that such a command asks for root permissions.
Besides besides besides... I agree on the fact that we should add a non-npm installation method.

**Comment by gggeek** [comment]
1. if I run 'npm run build', the build script by itself runs a subcommand 'npm install -g' to install bower => this is the cause of the problem. I do not think that it is a 'weird setup' to try to install an app without being root

**Comment by xbill82** [comment]
1. It would not be weird if `run build` was meant to install. It is actually just meant to _build_. It is the same difference between `make` (no root needed)  and `make install` (must be root, obviously). That being said, doing `npm install -g bower` within the build script is clearly an error (I mean, the `-g`).
2. the plain `npm install` does _not_ require admin rights, and this is the way you start a back office with no admin rights:

```bash
mkdir foo && cd foo
#  look ma, no sudo!
npm install kuzzle-backoffice
node_modules/.bin/kuzzle-backoffice start
```
Now, again, that being said... You're right, it's not documented!

Thanks!

**Comment by benoitvidis** [comment]
@xbill82 do we need to install bower globally? 

bower@1.8.0 with all its dependencies in an isolated installation takes 36M.
Compared to the 280M of the current bo dependencies, I would not be shocked to add it to the dev dependencies.

**Comment by xbill82** [comment]
@benoitvidis bower must be moved to devDependencies and must not be installed globally. To me, the actual state of both things is a total mistake and must be fixed (reason why I moved this issue to To Do).
