### ISSUE TITLE
Make the built backoffice available for download for every release

### ISSUE THREAD

**Issue by gggeek** [kuzzleio/kuzzle-backoffice#322]
It would simplify installation if the backoffice could be downloaded and installed without any need for NPM

**Comment by xbill82** [comment]
Npm is currently a very handy solution for us since
* it is publicly available and version-controlled with no effort
* it makes things easy when it comes to fetch and install (assuming you come from that culture).

Now, for non-nodejs people, there should be an alternative publishing platform. What would you advise?

**Comment by jenow** [comment]
You can also use the backoffice on netlify

**Comment by stafyniaksacha** [comment]
Maybe, a good thing will be to have `dist`  folder available into archives located in https://github.com/kuzzleio/kuzzle-backoffice/releases ?

**Comment by scottinet** [comment]
curl

**Comment by gggeek** [comment]
The whole point for me is to make it easy to install the backoffice for devs - and users - not coming from the js dev world.
It seems a bit of a waste to have a bo which is basically a static app (just a bunch of html, js and css) and force the users to either 'build' it or use a specific tool to install it.

My own preference is for a zip/tarball hosted on github, as Sascha mentioned.
Everyone and their dog understands how to handle that (unlike npm, heroku or netlify).

**Comment by xbill82** [comment]
Sounds legit to me

**Comment by scottinet** [comment]
@gggeek > That's what I meant. Something that can be get with a simple curl or wget command line.
This is also standard and easy to document.
