### ISSUE TITLE
Backoffice doesn't load if lastEnv's Kuzzle isn't up

### ISSUE THREAD

**Issue by BaptisteKaliop** [kuzzleio/kuzzle-backoffice#343]
I have 4 envs configured in my localStorage.

lastEnv's Kuzzle was down => Kuzzle BO doesn't start. I had to clean up my LocalStorage, and reconfigure the envs.

**Comment by AnthonySendra** [comment]
Duplicate of https://github.com/kuzzleio/kuzzle-backoffice/issues/329
Fixed by https://github.com/kuzzleio/kuzzle-backoffice/pull/339
