### ISSUE TITLE
cannot create profile on kuzzle-backoffice

### ISSUE THREAD

**Issue by plavacquery** [kuzzleio/kuzzle-backoffice#397]
I have a problem when editing profile on the kuzzle-backoffice interface, indeed when I tried to create new profile it sends me back 

**The request must specify the body attribute "policies" of type "array".
je précise que la création du profile avec le sdk ne pose aucun problème**

here above the profile 'profile1' I tried to set

```
{
 "policies": [
   {
     "roleId": "paul-role",
     "restrictedTo": [
       {
         "index": "a66",
         "collections": [{
           "a66-private"
         }]
       }
     ]
   }
 ]
} 

```
I precised that it works when I set the profile with the sdk

**Comment by Aschen** [comment]
There is a typo in your json, try with this one :  
```json
{
 "policies": [
   {
     "roleId": "paul-role",
     "restrictedTo": [
       {
         "index": "a66",
         "collections": [
           "a66-private"
         ]
       }
     ]
   }
 ]
} 
```

**Comment by plavacquery** [comment]
still have the same error

**Comment by Aschen** [comment]
The admin console version was `2.1.2` and the `2.1.3` had a bug fix for this problem https://github.com/kuzzleio/kuzzle-backoffice/pull/352.  
You can use the online admin console to ensure you are alway using the last version of the admin console : http://kuzzle-backoffice.netlify.com/
