### ISSUE TITLE
No collection delete feature in backoffice

### ISSUE THREAD

**Issue by teddybee** [kuzzleio/kuzzle-backoffice#404]
I haven't found the button in the backoffice and also in the api that deletes an empty collection. I can delete indexes I can delete documents, but for the collection I have to delete the whole index and create new collections again.

## Context (Environment)
I am using the newest docker image for kuzzle and npm package for backoffice. Logged in as an admin user. 
P.S.: kuzzle-backoffice docker image has a build error on dockerhub for 8 months.

**Comment by Tyki** [comment]
Hi,

That's because it's not possible due to ES limitations : 
https://www.elastic.co/guide/en/elasticsearch/reference/5.4/indices-delete-mapping.html
