### ISSUE TITLE
Collection mapping update error

### ISSUE THREAD

**Issue by teddybee** [kuzzleio/kuzzle-backoffice#405]
In the documentation I saw there is a mapping for each document in a collection.
I couldn't make the mapping without object name, I had to wrap like this:
```
"doc": {
    "properties": {
      "age": {
        "type": "integer"
      },
      "created": {
        "type": "date"
      },
      "name": {
        "type": "text"
      },
      "title": {
        "type": "text"
      }
    }
  }
```
After save I thought I edit the mapping, but after save there were two document kind in the mappings(e.g.: "doc:{...}" and docnew:{...} ). I had to fill in two forms when I want to add a document. There is no way to clear or update a mapping, even if I put only { }  in the mapping window.
As I cant delete the collection eighter I need to delete the whole index after this kind of typo.

## Expected Behavior
If I update the mapping of a collection, I would like to see only the last mapping structure that I typed in.

## Steps to Reproduce
1. Create a property mapping like I did above. Save.
2. Edit collection mapping, but change only the name of the "doc" to "docnew" and save. 
3. You will see there are two kind of forms in the new document menu as well as in the edit mapping.

## Context (Environment)
NodeJs 10.1, Windows 10, latest kuzzle-backoffice run from nodejs/npm directly.

**Comment by Aschen** [comment]
Hi,

You can't update an old field of the mapping, it's an Elasticsearch limitation.  
https://www.elastic.co/fr/blog/changing-mapping-with-zero-downtime
https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-put-mapping.html

You can only add new fields to your mapping
