### ISSUE TITLE
Impossible to trigger dropdown on a index tile

### ISSUE THREAD

**Issue by Tyki** [kuzzleio/kuzzle-backoffice#407]
I want to delete an index from the backoffice. But the "..." button is not clickable anymore. 
I'm almost sure there was a feature around this "..." button

## Expected Behavior

When I click on the "..." button, I have a dropdown giving me the possibility to delete an index from the backoffice
## Current Behavior

Nothing happened

## Steps to Reproduce

1. Go to http://kuzzle-backoffice.netlify.com
2. Create an index
3. Try to delete the index by clicking the "..." button > delete Index

## Context (Environment)

Kuzzle 1.2.10
No console error

**Comment by etrousset** [comment]
Hi, do your index have special characters in its name, as _ or other?

Hi,
There is an open issue on a bug preventing popup menu to show when index or collection's name contain some special char.

ping @Njuelle 

Cheers

**Comment by etrousset** [comment]
https://github.com/kuzzleio/kuzzle-backoffice/pull/361

**Comment by Tyki** [comment]
That's exactly my case

**Comment by Aschen** [comment]
Fixed but not deployed yet
