### ISSUE TITLE
Duplicate collection in treeview storage/realtime

### ISSUE THREAD

**Issue by AnthonySendra** [kuzzleio/kuzzle-backoffice#67]
How to reproduce?

* go to http://localhost:3000/#!/data/kuzzle-bo-testindex/editable-collection/watch
* click on subscribe
* open an other window on  http://localhost:3000/#!/data/kuzzle-bo-testindex/

Collection `editable-collection` is now in storage and in realtime. We have to exclude from realtime collections already in present in storage.

**Comment by xbill82** [comment]
Right, but this information comes from the Kuzzle Server, right? Shouldn't be a Server's concern to exclude the realtime collections if they are also persisted?

**Comment by AnthonySendra** [comment]
I'm not really sure... Because if the collection is duplicate in Storage AND in realtime, the front-end developer can choose to merge or not. But if the merge comes from the server, the front-end developer can't know the list of all realtime collections.

**Comment by stafyniaksacha** [comment]
We can add another icon for this kind of collection: there are persisted collections with realtime activity
