### ISSUE TITLE
Kuzzle Server Plugins Management

### ISSUE THREAD

**Issue by xbill82** [kuzzleio/kuzzle-backoffice#93]
We need a view to enable the user to manage the plugins server-side. Including
- adding a new plugin
- showing currently installed plugins
- enabling/disabling an installed plugin
- removing an installed plugin
- accessing/editing an installed plugin's configuration

**Warning** While developing these features, remember that Kuzzle Server needs to be restarted after every update

**Comment by gandbox** [comment]
Nope. Kuzzle is not Wordpress.
