### ISSUE TITLE
Improve error reporting 

### ISSUE THREAD

**Issue by stafyniaksacha** [kuzzleio/kuzzle-backoffice#97]
## Indexes:
* [ ] access to an un-existing index
* [x] create: add text to explain restrictions (can not have uppercase letters / nor begin with _ / ...)

## Collections:
* [ ] access to an un-existing collection (index exists)
* [ ] access to an un-existing collection (index does not exists)
* [x] create/update: display a bloc message instead a toast

## CRUDL Documents/Users/Profiles/Roles: 
* [x] create/update: bad mapping error (trying to set a field with another type that needed)
 * [ ] may we can display the mapping on the JSON mode ?
* [x] search with bad filers: actually there is no errors

## CRUDL Profiles/Roles: 
* [x] create/update: binding with bad document (profile -> roles, user->profiles)

## Watch: 
* [x] Subscribe with bad filters (Uncaught Error: Error during Kuzzle subscription: Unknown filter with name ...) 

## Login: 
* [x] Bad credentials
* [x] Error from backend on login (error on the auth plugin)

**Comment by xbill82** [comment]
Login errors? (Bad credentials, server panic, unknown error)

**Comment by jenow** [comment]
`Index` / `collection` does not exists
